// Compiled by ClojureScript 0.0-2371
goog.provide('medisoft.frontend.api.job_titles');
goog.require('cljs.core');
goog.require('medisoft.frontend.api.core');
goog.require('medisoft.frontend.api.core');
goog.require('medisoft.frontend.routes');
goog.require('medisoft.frontend.routes');
goog.require('medisoft.frontend.log');
goog.require('medisoft.frontend.log');
goog.require('medisoft.frontend.schemas');
goog.require('medisoft.frontend.schemas');
medisoft.frontend.api.job_titles.list = (function list(_,callback){return medisoft.frontend.api.core.api_call.call(null,new cljs.core.Keyword(null,"get","get",1683182755),medisoft.frontend.routes.server_path_for.call(null,new cljs.core.Keyword("api.job-titles","list","api.job-titles/list",26765042)),new cljs.core.PersistentArrayMap(null, 3, [new cljs.core.Keyword(null,"params","params",710516235),cljs.core.PersistentArrayMap.EMPTY,new cljs.core.Keyword(null,"schema","schema",-1582001791),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"response","response",-1068424192),medisoft.frontend.schemas.JobTitleListResponse], null),new cljs.core.Keyword(null,"response-fn","response-fn",377411189),callback], null));
});
medisoft.frontend.api.job_titles.get = (function get(p__16546,callback){var map__16548 = p__16546;var map__16548__$1 = ((cljs.core.seq_QMARK_.call(null,map__16548))?cljs.core.apply.call(null,cljs.core.hash_map,map__16548):map__16548);var id = cljs.core.get.call(null,map__16548__$1,new cljs.core.Keyword(null,"id","id",-1388402092));return medisoft.frontend.api.core.api_call.call(null,new cljs.core.Keyword(null,"get","get",1683182755),medisoft.frontend.routes.server_path_for.call(null,new cljs.core.Keyword("api.job-titles","show","api.job-titles/show",1907233824),new cljs.core.Keyword(null,"id","id",-1388402092),id),new cljs.core.PersistentArrayMap(null, 3, [new cljs.core.Keyword(null,"params","params",710516235),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"id","id",-1388402092),id], null),new cljs.core.Keyword(null,"schema","schema",-1582001791),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"response","response",-1068424192),medisoft.frontend.schemas.JobTitleShowResponse], null),new cljs.core.Keyword(null,"response-fn","response-fn",377411189),callback], null));
});
medisoft.frontend.api.job_titles.create = (function create(p__16549,callback){var map__16551 = p__16549;var map__16551__$1 = ((cljs.core.seq_QMARK_.call(null,map__16551))?cljs.core.apply.call(null,cljs.core.hash_map,map__16551):map__16551);var params = map__16551__$1;return medisoft.frontend.api.core.api_call.call(null,new cljs.core.Keyword(null,"post","post",269697687),medisoft.frontend.routes.server_path_for.call(null,new cljs.core.Keyword("api.job-titles","create","api.job-titles/create",242125833)),new cljs.core.PersistentArrayMap(null, 3, [new cljs.core.Keyword(null,"params","params",710516235),params,new cljs.core.Keyword(null,"schema","schema",-1582001791),new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"request","request",1772954723),medisoft.frontend.schemas.JobTitleCreateRequest,new cljs.core.Keyword(null,"response","response",-1068424192),medisoft.frontend.schemas.JobTitleCreateResponse], null),new cljs.core.Keyword(null,"response-fn","response-fn",377411189),callback], null));
});
medisoft.frontend.api.job_titles.update = (function update(p__16552,callback){var map__16554 = p__16552;var map__16554__$1 = ((cljs.core.seq_QMARK_.call(null,map__16554))?cljs.core.apply.call(null,cljs.core.hash_map,map__16554):map__16554);var params = map__16554__$1;var id = cljs.core.get.call(null,map__16554__$1,new cljs.core.Keyword(null,"id","id",-1388402092));return medisoft.frontend.api.core.api_call.call(null,new cljs.core.Keyword(null,"put","put",1299772570),medisoft.frontend.routes.server_path_for.call(null,new cljs.core.Keyword("api.job-titles","update","api.job-titles/update",442257739),new cljs.core.Keyword(null,"id","id",-1388402092),id),new cljs.core.PersistentArrayMap(null, 3, [new cljs.core.Keyword(null,"params","params",710516235),cljs.core.dissoc.call(null,params,new cljs.core.Keyword(null,"id","id",-1388402092)),new cljs.core.Keyword(null,"schema","schema",-1582001791),new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"request","request",1772954723),medisoft.frontend.schemas.JobTitleUpdateRequest,new cljs.core.Keyword(null,"response","response",-1068424192),medisoft.frontend.schemas.JobTitleUpdateResponse], null),new cljs.core.Keyword(null,"response-fn","response-fn",377411189),callback], null));
});

//# sourceMappingURL=job_titles.js.map