// Compiled by ClojureScript 0.0-2371
goog.provide('medisoft.frontend.api.medicines');
goog.require('cljs.core');
goog.require('medisoft.frontend.api.core');
goog.require('medisoft.frontend.api.core');
goog.require('medisoft.frontend.routes');
goog.require('medisoft.frontend.routes');
goog.require('medisoft.frontend.log');
goog.require('medisoft.frontend.log');
goog.require('medisoft.frontend.schemas');
goog.require('medisoft.frontend.schemas');
medisoft.frontend.api.medicines.list = (function list(_,callback){return medisoft.frontend.api.core.api_call.call(null,new cljs.core.Keyword(null,"get","get",1683182755),medisoft.frontend.routes.server_path_for.call(null,new cljs.core.Keyword("api.medicines","list","api.medicines/list",-247043712)),new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"schema","schema",-1582001791),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"response","response",-1068424192),medisoft.frontend.schemas.MedicineListResponse], null),new cljs.core.Keyword(null,"response-fn","response-fn",377411189),callback], null));
});
medisoft.frontend.api.medicines.get = (function get(p__16886,callback){var map__16888 = p__16886;var map__16888__$1 = ((cljs.core.seq_QMARK_.call(null,map__16888))?cljs.core.apply.call(null,cljs.core.hash_map,map__16888):map__16888);var id = cljs.core.get.call(null,map__16888__$1,new cljs.core.Keyword(null,"id","id",-1388402092));return medisoft.frontend.api.core.api_call.call(null,new cljs.core.Keyword(null,"get","get",1683182755),medisoft.frontend.routes.server_path_for.call(null,new cljs.core.Keyword("api.medicines","show","api.medicines/show",1631066486),new cljs.core.Keyword(null,"id","id",-1388402092),id),new cljs.core.PersistentArrayMap(null, 3, [new cljs.core.Keyword(null,"params","params",710516235),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"id","id",-1388402092),id], null),new cljs.core.Keyword(null,"schema","schema",-1582001791),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"response","response",-1068424192),medisoft.frontend.schemas.MedicineShowResponse], null),new cljs.core.Keyword(null,"response-fn","response-fn",377411189),callback], null));
});
medisoft.frontend.api.medicines.create = (function create(p__16889,callback){var map__16891 = p__16889;var map__16891__$1 = ((cljs.core.seq_QMARK_.call(null,map__16891))?cljs.core.apply.call(null,cljs.core.hash_map,map__16891):map__16891);var params = map__16891__$1;return medisoft.frontend.api.core.api_call.call(null,new cljs.core.Keyword(null,"post","post",269697687),medisoft.frontend.routes.server_path_for.call(null,new cljs.core.Keyword("api.medicines","create","api.medicines/create",-564883165)),new cljs.core.PersistentArrayMap(null, 3, [new cljs.core.Keyword(null,"params","params",710516235),params,new cljs.core.Keyword(null,"schema","schema",-1582001791),new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"request","request",1772954723),medisoft.frontend.schemas.MedicineCreateRequest,new cljs.core.Keyword(null,"response","response",-1068424192),medisoft.frontend.schemas.MedicineCreateResponse], null),new cljs.core.Keyword(null,"response-fn","response-fn",377411189),callback], null));
});
medisoft.frontend.api.medicines.update = (function update(p__16892,callback){var map__16894 = p__16892;var map__16894__$1 = ((cljs.core.seq_QMARK_.call(null,map__16894))?cljs.core.apply.call(null,cljs.core.hash_map,map__16894):map__16894);var params = map__16894__$1;var id = cljs.core.get.call(null,map__16894__$1,new cljs.core.Keyword(null,"id","id",-1388402092));return medisoft.frontend.api.core.api_call.call(null,new cljs.core.Keyword(null,"put","put",1299772570),medisoft.frontend.routes.server_path_for.call(null,new cljs.core.Keyword("api.medicines","update","api.medicines/update",174727725),new cljs.core.Keyword(null,"id","id",-1388402092),id),new cljs.core.PersistentArrayMap(null, 3, [new cljs.core.Keyword(null,"params","params",710516235),cljs.core.dissoc.call(null,params,new cljs.core.Keyword(null,"id","id",-1388402092)),new cljs.core.Keyword(null,"schema","schema",-1582001791),new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"request","request",1772954723),medisoft.frontend.schemas.MedicineUpdateRequest,new cljs.core.Keyword(null,"response","response",-1068424192),medisoft.frontend.schemas.MedicineUpdateResponse], null),new cljs.core.Keyword(null,"response-fn","response-fn",377411189),callback], null));
});

//# sourceMappingURL=medicines.js.map